Repository MLH-Fellowship/jan-2022-prep-portfolio, pull requests merged in 2022-01, with the labels that each got.

#36 Enhacement: Added Pod details
  _config.yml
  _data/fellows.yml
  assets/img/Kish.jpeg
  assets/img/Sahithi.jpeg
  assets/img/advitiay.jpg
  assets/img/anubhav.jpg
  assets/img/dhruv.jpg
  assets/img/emeka.JPG
  assets/img/harsh.png
  assets/img/kshitij.jpg
  assets/img/nomani.jpg
  assets/img/pal.jpg
  assets/img/pritish.jpeg
  assets/img/riya.png
  assets/img/tushar.png
  assets/img/vaibhave.jpg
  assets/img/yan.jpg
Labels: ready to merge

#35 feat: Added page transitions. [#25]
  _includes/header.html
  _includes/page-transition.html
  _layouts/default.html
  _sass/all.scss
  _sass/darkmode.scss
  _sass/page-transition.scss
  assets/js/page-transition.js
  index.html
Labels: ready to merge

#47 fix: Fixed a compatibility issue with darkmode and page-transition
  _includes/page-transition.html
  _includes/toggle.html
  _sass/darkmode.scss
  assets/js/toggle.js
Labels: bug, quick fix

#49 fix: page-transition breaks when the href starts with #
  _includes/footer.html
  assets/js/page-transition.js
Labels: quick fix

#61 feat: Experimental: Capture the browser's back/forward events and transit between pages
  assets/js/page-transition.js
Labels: enhancement
